[thanos] Add persistentVolumeClaim in rule component
banzaicloud/banzai-charts pull request #1192
Opened 2020-11-24 18:34 UTC by JohnWillker

| Q               | A
| --------------- | ---
| Bug fix?        | no|yes
| New feature?    | yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | no
| License         | Apache 2.0

### What's in this PR?

Using Ruler for global rules evaluation in an [HA](https://thanos.io/tip/components/rule.md/#ruler-ha) mode, we have some problems when the rule pod dies, like lost all last 2h. To fix this problem we need to use a PersistentVolumeClain just like in Compact or in Prometheus in case of pod restart we maintain the data until the next upload to Bucket.

### Why?

Persist Ruler data for an HA use case.(Don't' lost data in ruler restarts)

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

2020-11-25 09:29 UTC, tarokkk requested changes
Thank you for your contribution. I simplified it a little bit.

2020-11-25 09:29 UTC, tarokkk commented on thanos/templates/rule-statefulset.yaml
> +      {{- if not .Values.rule.dataVolume.backend }}
```suggestion
      {{- if not .Values.rule.persistentVolumeClaim }}
```

2020-11-25 09:29 UTC, tarokkk commented on thanos/README.md
> +| rule.dataVolume.backend    | Data volume for the rule to store temporary data defaults to emptyDir.      | {} |
```suggestion
```

2020-11-25 09:29 UTC, tarokkk commented on thanos/values.yaml
> +  # Data volume for the rule to store temporary data defaults to emptyDir
Please remove this dataVolume part

2020-11-25 14:37 UTC, JohnWillker commented on thanos/values.yaml
> +    #    claimName: rule-data-volume
```suggestion
```

2020-11-25 14:50 UTC, JohnWillker commented on thanos/templates/rule-statefulset.yaml
> +      name: {{ .Values.rule.dataVolume.backend.persistentVolumeClaim.claimName }}
```suggestion
      name: {{ .Values.rule.persistentVolumeClaim.name }}
```

2020-11-25 15:20 UTC, tarokkk approved these changes

2020-11-28 21:02 UTC, JohnWillker commented
@tarokkk Merge?

2020-12-13 13:25 UTC, ahma approved these changes
Thanks @JohnWillker LGTM

2020-12-13 13:26 UTC, merged