add deprecation notice for Spark & Zeppelin charts
banzaicloud/banzai-charts pull request #1246
Opened 2021-04-23 08:22 UTC by sancyx

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| API breaks?     | no
| Deprecations?   | yes
| License         | Apache 2.0

### What's in this PR?
Add deprecation notice for Spark & Zeppelin charts

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

2021-04-23 09:07 UTC, pregnor requested changes
Please also set the chart's `Chart.yaml`'s `deprecated` field to `true` similarly to https://github.com/helm/charts/pull/21247/files

2021-04-23 09:33 UTC, pregnor approved these changes

2021-05-26 14:34 UTC, ahma approved these changes

2021-05-26 15:01 UTC, merged

2021-06-17 15:48 UTC, ebuildy commented
Hello, just curious, why Zeppelin chart have been deprecated? Is there an alternative or a fork? thanks you